---
- name: Check if GitLab user {{ gitlab_username }} already exists
  ansible.builtin.set_fact:
    _existing_user: "{{ r_gitlab_users.json | selectattr('username', 'equalto', gitlab_username) | list }}"

- name: Create GitLab user {{ gitlab_username }} if not exists
  ansible.builtin.uri:
    url: "https://{{ idp_lab_from0_gitlab_config_host }}/api/v4/users"
    method: POST
    body_format: form-urlencoded
    body:
      admin: false
      email: "{{ gitlab_username }}@rhdemo.com"
      public_email: "{{ gitlab_username }}@rhdemo.com"
      skip_confirmation: true
      username: "{{ gitlab_username }}"
      password: "{{ common_password }}"
      name: "{{ gitlab_username }} GitLab"
    headers:
      PRIVATE-TOKEN: "{{ _idp_lab_from0_gitlab_root_token }}"
    validate_certs: false
    status_code: [201, 409]
  when: _existing_user | length == 0

- name: Reset password of GitLab user {{ gitlab_username }} to common_password
  ansible.builtin.uri:
    url: "https://{{ idp_lab_from0_gitlab_config_host }}/api/v4/users/{{ _existing_user[0].id }}"
    method: PUT
    body_format: form-urlencoded
    body:
      password: "{{ common_password }}"
      skip_reconfirmation: true
    headers:
      PRIVATE-TOKEN: "{{ _idp_lab_from0_gitlab_root_token }}"
    validate_certs: false
    status_code: 200
  when: _existing_user | length > 0
