---
- name: Install OpenShift GitOps operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ idp_lab_from0_openshift_gitops_operator_name }}"
    install_operator_namespace: "{{ idp_lab_from0_openshift_gitops_operator_namespace }}"
    install_operator_channel: "{{ idp_lab_from0_openshift_gitops_operator_channel }}"
    install_operator_catalog: "{{ idp_lab_from0_openshift_gitops_operator_catalog }}"
    install_operator_automatic_install_plan_approval: >-
      {{ idp_lab_from0_openshift_gitops_operator_automatic_install_plan_approval | default(true) }}
    install_operator_starting_csv: "{{ idp_lab_from0_openshift_gitops_operator_starting_csv }}"
    install_operator_catalogsource_setup: >-
      {{ idp_lab_from0_openshift_gitops_operator_use_catalog_snapshot | default(false) }}
    install_operator_catalogsource_name: >-
      {{ idp_lab_from0_openshift_gitops_operator_catalogsource_name | default('') }}
    install_operator_catalogsource_namespace: >-
      {{ idp_lab_from0_openshift_gitops_operator_catalogsource_namespace | default('') }}
    install_operator_catalogsource_image: >-
      {{ idp_lab_from0_openshift_gitops_operator_catalog_snapshot_image | default('') }}
    install_operator_catalogsource_image_tag: >-
      {{ idp_lab_from0_openshift_gitops_operator_catalog_snapshot_image_tag | default('') }}
    install_operator_subscription_config: "{{ idp_lab_from0_openshift_gitops_operator_config }}"

- name: Grant cluster-admin permissions to GitOps service account
  when: idp_lab_from0_openshift_gitops_setup_cluster_admin | bool
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'openshift_gitops_clusterrolebinding.yaml') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: git_sa_result
  until: git_sa_result is not failed

- name: Print git_sa_result
  ansible.builtin.debug:
    var: git_sa_result

- name: Wait until openshift-gitops ArgoCD instance has been created
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
  register: r_openshift_gitops
  until:
    - r_openshift_gitops is defined
    - r_openshift_gitops.resources is defined
    - r_openshift_gitops.resources | length == 1
  ignore_errors: true
  retries: 10
  delay: 30

- name: Print r_openshift_gitops
  ansible.builtin.debug:
    var: r_openshift_gitops

- name: Update resources for openshift-gitops ArgoCD instance
  when: idp_lab_from0_openshift_gitops_update_resources | bool
  kubernetes.core.k8s:
    state: patched
    definition: "{{ lookup('template', 'openshift-gitops/openshift-gitops.yaml.j2') | from_yaml }}"
  retries: 10
  delay: 30
  ignore_errors: true
  register: openshift_gitops_result
  until: openshift_gitops_result is not failed

- name: Print openshift_gitops_result
  ansible.builtin.debug:
    var: openshift_gitops_result

- name: Remove memory limit for ArgoCD controller
  when: idp_lab_from0_openshift_gitops_controller_remove_memory_limits | bool
  kubernetes.core.k8s_json_patch:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
    patch:
      - op: remove
        path: /spec/controller/resources/limits/memory
  retries: 10
  delay: 30
  ignore_errors: true
  register: openshift_gitops_rm_mem_result
  until: openshift_gitops_rm_mem_result is not failed

- name: Retrieve openshift-gitops-cluster secret
  kubernetes.core.k8s_info:
    api_version: "v1"
    kind: Secret
    name: openshift-gitops-cluster
    namespace: openshift-gitops
  register: r_secret
  until:
    - r_secret is defined
    - r_secret.resources is defined
    - r_secret.resources | length == 1
  retries: 10
  delay: 30
  ignore_errors: true

- name: Set openshift_gitops_admin_password fact
  ansible.builtin.set_fact:
    openshift_gitops_admin_password: "{{ r_secret.resources[0]['data']['admin.password'] | string | b64decode }}"

- name: Ensure cluster-admins OpenShift group exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: cluster-admins
      users: "{{ idp_lab_from0_openshift_gitops_cluster_admins_group_users }}"

- name: Register GitLab helm repo in ArgoCD (with root token for authentication)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-repo-gitlab-helm
        namespace: openshift-gitops
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      stringData:
        type: git
        url: "https://gitlab-{{ idp_lab_from0_gitlab_namespace }}.{{ r_openshift_subdomain }}/idp-lab/helm.git"
        username: root
        password: "{{ idp_lab_from0_gitlab_config_root_password }}"

- name: Print ArgoCD access information
  ansible.builtin.debug:
    msg:
      - "openshift_gitops_user: admin"
      - "openshift_gitops_password: {{ openshift_gitops_admin_password }}"
