---
- name: Post-workload tasks complete
  ansible.builtin.debug:
    msg:
      - "Post-Workload tasks completed successfully."
      - "Showroom URL: {{ _showroom_url | default('N/A') }}"
      - "GitLab URL: {{ _gitlab_url | default('GitLab deployment in progress') }}"
      - "Common Password: {{ common_password }}"
  when:
    - not silent | bool
