{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "idp-lab.fullname" . }}
  labels:
    {{- include "idp-lab.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave.rbac | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "idp-lab.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "idp-lab.serviceAccountName" . }}
    namespace: {{ .Values.namespace.name }}
{{- end }}
