{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "idp-lab.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
