---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: showroom-restart
  namespace: showroom
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
